### PR TITLE
Make the repo easily buildable and add changes from when I worked on rocm

### PR DESCRIPTION
**Pull request by Tzigamm**
I added the common folder and the Makefiles needed to build the repo as soon as it's cloned, I also changed the package.yml of the thunk, the runtime and numactl. It now relies a bit more on patches and less on big lists of instructions in package.yml

### CODE REVIEW

**Comment by saitam757** [comment]
Good Idea.

**Comment by algent-al** [comment]
or just make a simple script to do all that stuff.

**Comment by Tzigamm** [comment]
@algent-al you mean like a script that would download common, make the symlinks and create the makefiles ? That could work, but is it really better than having them in tree?

**Comment by algent-al** [comment]
With a script make this repo more simple. It is just an idea.

**Comment by Tzigamm** [comment]
Yeah I get it, in theory your approach is better cause it would make this repo's source tree cleaner, but if we expect everyone to download the files maybe having them in tree is a better approach... Waiting on @emaimx's input, if the script approach is preferable I'll amend this pull request (at least I think it's possible? If not just close it and I'll open another one)

**Comment by emaimx** [comment]
I don't mind having the common folder here. Thank you for the rest of your commit.

**Pull request merged**
